name: Deploy

on:
  push:
    branches:
      - main


jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secret.HEROKU_API_KEY}}
        heroku_app_name: ${{secret.HEROKU_APP_NAME}}
        heroku_email: ${{secret.HEROKU_EMAIL}}
